version: '3'
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    # 8.x
    environment:
      ELASTIC_USERNAME: elastic
      ELASTIC_PASSWORD: elastic
      bootstrap.memory_lock: true
      discovery.type: single-node
      xpack.security.enabled: false
      xpack.security.enrollment.enabled: true
      xpack.security.transport.ssl.enabled: false
      xpack.security.http.ssl.enabled: false
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1g
        reservations:
          cpus: '1.0'
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    container_name: kibana
    environment:
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: d1a66dfd-c4d3-4a0a-8290-2abcb83ab3aa
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512m
        reservations:
          cpus: '1.0'
    volumes:
      - kibana-config:/usr/share/kibana/config

volumes:
  elasticsearch-data:
  kibana-config:
